name: "ForgeDeploy"
description: "Deploy and optionally install a Forge app using Forge CLI"

inputs:
  email:
    description: "Atlassian account email"
    required: true
  apiToken:
    description: "Atlassian API token"
    required: true
  environment:
    description: "Forge environment to deploy to (e.g. development, staging, production)"
    required: true
  siteUrl:
    description: "Atlassian site URL (e.g. yourcompany.atlassian.net)"
    required: false
  product:
    description: "Atlassian product to deploy to (e.g. jira, confluence)"
    required: true
  installToSite:
    description: "Set to false to skip 'forge install' (e.g. if app is already installed)"
    required: false
    default: "true"
  isCustomApp:
    description: "Set to true if this is a custom Forge app in a subdirectory"
    required: false
    default: "false"
  customAppPath:
    description: "Path to custom Forge app (relative to repo root)"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install Forge CLI
      run: npm install -g @forge/cli
      shell: bash

    - name: Install root backend dependencies
      run: npm install
      shell: bash

    - name: Check for manifest.yml (custom app)
      if: inputs.isCustomApp == 'true'
      run: |
        if [ ! -f "${CUSTOM_APP_PATH}/manifest.yml" ]; then
          echo "manifest.yml not found in custom app path: ${CUSTOM_APP_PATH}"
          exit 1
        fi
      shell: bash
      env:
        CUSTOM_APP_PATH: ${{ inputs.customAppPath }}

    - name: Check for manifest.yml (non-custom app)
      if: inputs.isCustomApp != 'true'
      run: |
        if [ ! -f "manifest.yml" ]; then
          echo "manifest.yml not found at repo root"
          exit 1
        fi
      shell: bash

    - name: Install frontend dependencies (custom app only)
      if: inputs.isCustomApp == 'true'
      run: npm install
      shell: bash
      working-directory: ${{ inputs.customAppPath }}

    - name: Build frontend (custom app only)
      if: inputs.isCustomApp == 'true'
      run: npm run build
      shell: bash
      working-directory: ${{ inputs.customAppPath }}

    - name: Disable Forge usage analytics
      run: forge settings set usage-analytics false
      shell: bash
      working-directory: ${{ inputs.isCustomApp == 'true' && inputs.customAppPath || '.' }}

    - name: Deploy Forge app
      run: forge deploy --environment "${ENVIRONMENT}" --non-interactive
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        FORGE_EMAIL: ${{ inputs.email }}
        FORGE_API_TOKEN: ${{ inputs.apiToken }}
      working-directory: ${{ inputs.isCustomApp == 'true' && inputs.customAppPath || '.' }}

    - name: Install Forge app (optional)
      if: inputs.installToSite != 'false'
      run: |
        forge install \
          --product "${PRODUCT}" \
          --site "${SITE_URL}" \
          --environment "${ENVIRONMENT}" \
          --non-interactive
      shell: bash
      env:
        INSTALL_TO_SITE: ${{ inputs.installToSite }}
        PRODUCT: ${{ inputs.product }}
        SITE_URL: ${{ inputs.siteUrl }}
        ENVIRONMENT: ${{ inputs.environment }}
        FORGE_EMAIL: ${{ inputs.email }}
        FORGE_API_TOKEN: ${{ inputs.apiToken }}
      working-directory: ${{ inputs.isCustomApp == 'true' && inputs.customAppPath || '.' }}
