name: "ForgeDeploy"
description: "Deploy and optionally install a Forge app using Forge CLI"

inputs:
  email:
    description: "Atlassian account email"
    required: true
  apiToken:
    description: "Atlassian API token"
    required: true
  environment:
    description: "Forge environment to deploy to (e.g. development, staging, production)"
    required: true
  siteUrl:
    description: "Atlassian site URL (e.g. yourcompany.atlassian.net)"
    required: false
  product:
    description: "Atlassian product to deploy to (e.g. jira, confluence)"
    required: true
  installToSite:
    description: "Set to false to skip 'forge install' (e.g. if app is already installed)"
    required: false
    default: "true"
  isCustomApp:
    description: "Set to true if this is a custom Forge app in a subdirectory"
    required: false
    default: "false"
  customAppPath:
    description: "Path to custom Forge app (relative to repo root)"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install Forge CLI
      run: npm install -g @forge/cli
      shell: bash

    - name: Install root backend dependencies
      run: |
        npm install
      shell: bash

    - name: Install frontend dependencies (custom UI)
      run: |
        IS_CUSTOM_APP=${IS_CUSTOM_APP:-false}
        CUSTOM_APP_PATH=${CUSTOM_APP_PATH:-.}
        if [[ "$IS_CUSTOM_APP" == "true" ]]; then
          cd "$CUSTOM_APP_PATH"
          npm install
        fi
      shell: bash
      env:
        IS_CUSTOM_APP: ${{ inputs.isCustomApp }}
        CUSTOM_APP_PATH: ${{ inputs.customAppPath }}

    - name: Build frontend (custom UI)
      run: |
        IS_CUSTOM_APP=${IS_CUSTOM_APP:-false}
        CUSTOM_APP_PATH=${CUSTOM_APP_PATH:-.}
        if [[ "$IS_CUSTOM_APP" == "true" ]]; then
          cd "$CUSTOM_APP_PATH"
          npm run build
        fi
      shell: bash
      env:
        IS_CUSTOM_APP: ${{ inputs.isCustomApp }}
        CUSTOM_APP_PATH: ${{ inputs.customAppPath }}

    - name: Disable usage analytics
      run: forge settings set usage-analytics false
      shell: bash

    - name: Deploy Forge app
      run: |
        forge deploy --environment "${ENVIRONMENT}" --non-interactive
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        FORGE_EMAIL: ${{ inputs.email }}
        FORGE_API_TOKEN: ${{ inputs.apiToken }}

    - name: Install Forge app (optional)
      run: |
        INSTALL_TO_SITE=${INSTALL_TO_SITE:-true}
        if [[ "$INSTALL_TO_SITE" == "true" ]]; then
          forge install --product "${PRODUCT}" --site "${SITE_URL}" --environment "${ENVIRONMENT}" --non-interactive
        fi
      shell: bash
      env:
        INSTALL_TO_SITE: ${{ inputs.installToSite }}
        PRODUCT: ${{ inputs.product }}
        SITE_URL: ${{ inputs.siteUrl }}
        ENVIRONMENT: ${{ inputs.environment }}
        FORGE_EMAIL: ${{ inputs.email }}
        FORGE_API_TOKEN: ${{ inputs.apiToken }}
